; ************************************************************************
; Project: Lemon - Simple 6502 Monitor
; Author: Bryce Simonds
; License: BSD 3-Clause
; File: hotkey.inc
; Description: Codes for editor hot keys
;
; Copyright (c) 2023
; ************************************************************************

.define KEY_UNKNOWN 0
.define KEY_UP      1
.define KEY_DOWN    2
.define KEY_RIGHT   3
.define KEY_LEFT    4
.define KEY_HOME    5
.define KEY_END     6
.define KEY_DELETE  7
.define KEY_INSERT  8
.define KEY_PU      9
.define KEY_PD      10

; ************************************************************************

